package com.company.enums;

public enum UserStatus {

    NEW,
    LANGUAGE,
    HAS_CONTACT,
    HOBBY,
    GENDER,

    MENU,
    SETTING,
    CONTACT_ADMIN,
    WRITE_COMPLAINT,
    SENDING_REKLAMA,
    USER_CONVERSATION,
    USER_FOLLOWER_BUTTON,
    USER_GET_CONTACT,
    USER_GET_TELEGRAM_ID,
    USER_WROTE_OTHER,

    ADMIN_WRITE_RESPONSE,
    ADMIN_MENU,
    ADMIN_PUT_REKLAMA,

}
